### ISSUE TITLE
server.ts file import ultra from "http://172.20.10.6:8080/mod.ts";

### ISSUE THREAD

**Issue by 5u4** [exhibitionist-digital/ultra-examples#1]
Hi, I came from https://ultrajs.dev/examples and wanna try out ultra.

I found that `server.ts` imports ultra from an unaccessible address http://172.20.10.6:8080/mod.ts.

I am stuck on downloading the ultra.

```
❯ make    
mode=dev deno run --allow-net --allow-read --allow-run --allow-env --allow-write --no-check --import-map importmap.json --unstable server.ts
Download http://172.20.10.6:8080/mod.ts
```

---

On the quick start tutorial https://ultrajs.dev/docs, it says I should `import ultra from "https://ultra.land/x/ultra/mod.ts"` which I also cannot access.

---

I tried `import ultra from "https://deno.land/x/ultra/mod.ts"` then it gave me the error

```
❯ make
mode=dev deno run --allow-net --allow-read --allow-run --allow-env --allow-write --no-check --import-map importmap.json --unstable server.ts
error: Relative import path "helmet" not prefixed with / or ./ or ../ and not in import map from "https://deno.land/x/ultra@v0.6/src/render.ts"
    at https://deno.land/x/ultra@v0.6/src/render.ts:4:32
make: *** [dev] Error 1
```

Could anyone help me to resolve the issue? Thanks!

**Comment by mashaal** [comment]
Hi @5u4 -- These examples were using a local build of Ultra, I have just updated all of the imports with the recently publish v0.7.0
