### ISSUE TITLE
importmap.json should be importMap.json inside vscode settings

### ISSUE THREAD

**Issue by dannybucksch** [exhibitionist-digital/ultra-examples#4]
vscode can not  find the import map with the current settings.json, as it references an importmap in all lowercase.

it should be:
"deno.importMap": "./importMap.json",

see:
https://github.com/exhibitionist-digital/ultra-examples/blob/49f8b527c122345dea1c175b5bc80d4911b85efd/.vscode/settings.json#L5

cheers and thx

**Comment by mashaal** [comment]
Thanks, we missed that when updating our casing for the importMaps recently. This should be fixed now
